name: Send Email on New File

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect Changed File
        id: detect_file
        run: |
          # Commit lo change/add ayina modati file name ni teesukuntundi
          CHANGED_FILE=$(git diff --name-only HEAD~1 HEAD | head -n 1)
          echo "Found file: $CHANGED_FILE"
          echo "file_path=$CHANGED_FILE" >> $GITHUB_OUTPUT

      - name: Send Email with Dynamic Attachment
        if: ${{ steps.detect_file.outputs.file_path != '' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: 587
          secure: false
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_FROM }}
          to: ${{ secrets.EMAIL_TO }}
          subject: New File Uploaded to GitHub
          body: |
            Hi, A new file has been pushed to the repository.
            
            File Name: ${{ steps.detect_file.outputs.file_path }}
          # Ee line automation ni chuskuntundi, hardcode avasaram ledu
          attachments: ${{ steps.detect_file.outputs.file_path }}
